baseurl = "https://lokilike.netlify.app/"
title = "Seungjae Oh"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-139247202-1"

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "blue"
  description = "Describe your website"
  copyright = "&copy;2025 Seungjae Oh"
  sidebarAbout = [
    "I am a Human-Computer Interaction researcher interested in Haptics and Sensing Technologies",
  ]
  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "seungjae.oh7@gmail.com"

  # Nav links in the side bar
  [[params.navlinks]]
  name = "About"
  url = "about/"
  

  [[params.navlinks]]
  name = "Research"
  url = "research/"
  home = true

  [[params.navlinks]]
  name = "Design"
  url = "design/"

  [[params.navlinks]]
  name = "Contact"
  url = "contact/"


  [params.social]
#  facebook      = "https://www.facebook.com/seungjae.oh7"
  lab           = "https://khuhit.netlify.app/"
  video         = "https://www.youtube.com/@KHUInteractivetechnology"
  email         = "oreo329@khu.ac.kr"
  youtube       = "https://www.youtube.com/user/seungjae329" 
  linkedin      = "https://www.linkedin.com/in/seungjae329/"
